// Generates src/lib/psl-data.js from the ICANN section of the Public Suffix List.
// Usage: node scripts/gen-psl.mjs   (expects scripts/public_suffix_list.dat)
import { readFileSync, writeFileSync } from 'node:fs';
import { domainToASCII } from 'node:url';

const raw = readFileSync(new URL('./public_suffix_list.dat', import.meta.url), 'utf8');
const icann = raw.split('// ===END ICANN DOMAINS===')[0];

const rules = new Set();
for (let line of icann.split('\n')) {
  line = line.trim();
  if (!line || line.startsWith('//')) continue;
  let prefix = '';
  if (line.startsWith('!')) { prefix = '!'; line = line.slice(1); }
  const labels = line.split('.').map((l) => (l === '*' ? '*' : domainToASCII(l) || l));
  rules.add(prefix + labels.join('.'));
}

const body = [...rules].sort().join(' ');
const out = `// Generated by scripts/gen-psl.mjs from the Public Suffix List (ICANN section).
// Source: https://publicsuffix.org/list/ — Mozilla Public License 2.0.
export const PSL_RULES = ${JSON.stringify(body)};
`;
writeFileSync(new URL('../src/lib/psl-data.js', import.meta.url), out);
console.log(`psl-data.js: ${rules.size} rules, ${out.length} bytes`);
